apiVersion: v1
kind: ServiceAccount
metadata:
  name: aviary
imagePullSecrets:
- name: registry-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aviary
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - pods
  - deployments
  - deployments/scale
  verbs:
  - update
  - create
  - get
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aviary
subjects:
  - kind: ServiceAccount
    name: aviary
roleRef:
  kind: Role
  name: aviary
  apiGroup: rbac.authorization.k8s.io
